package com.heaven4.engines.operations;

import lombok.Builder;
import lombok.Getter;

/**
 * Alert/recommendation generated by the Smart Operations Assistant.
 */
@Getter
@Builder
public class OperationalAlert {

    private String alertId;
    private String type;         // ALERT, RECOMMENDATION, INFO
    private String severity;     // CRITICAL, WARNING, INFO
    private String title;
    private String message;
    private String category;     // TABLE, KITCHEN, EMPLOYEE, CUSTOMER, SYSTEM
    private Long referenceId;
    private String referenceType;
    private String suggestedAction;
    private String deepLink;
    private java.time.Instant timestamp;
}
